# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Docker Image CI

on:
  push:
    branches: [ "main" ] # 기존 dev branch 삭제, 혼자 개발 하기 때문에 main만 있으면 충분하다고 판단, 그러나 무중단 배포를 위해서 추 후 dev할 예정
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # jdk 21 세팅
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 패키징
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # 도커 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 도커 이미지 빌드
      - name: Build the Docker image
        run: docker build -t 10m24s/mybooks-gateway .

      # 이미지 띄우기
      - name: push Docker image
        run: docker push 10m24s/mybooks-gateway

      # 쉘 스크립트 실행
      - name: execute shell script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: "./mybooks/gateway_startup.sh"